#!/bin/bash
# Author:  Michal Ambroz <rebus@seznam.cz>
# License: GPLv2+
#
#     Copyright (C) 2018  Michal Ambroz <rebus@seznam.cz>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Example:
#     grepsha256 malware.vba
#     ... look for strings, which might be SHA256 checksums


#grep --color -i -P -e '(?<![a-fA-F0-9])(?<!id=\")(?<!Key: '"'"'|serv='"'"')[a-fA-F0-9]{64}(?![a-fA-F0-9])(?!\.js|\.png|\.css)' $*
grep --color -i -P -e '(?<![a-f0-9])[a-f0-9]{64}(?![a-f0-9])' "$@"



